# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nicola/Workspace/Genny

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nicola/Workspace/Genny

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicola/Workspace/Genny/CMakeFiles /home/nicola/Workspace/Genny/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicola/Workspace/Genny/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Genny

# Build rule for target.
Genny: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Genny
.PHONY : Genny

# fast build rule for target.
Genny/fast:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/build
.PHONY : Genny/fast

#=============================================================================
# Target rules for targets named cudaRO

# Build rule for target.
cudaRO: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudaRO
.PHONY : cudaRO

# fast build rule for target.
cudaRO/fast:
	$(MAKE) -f CMakeFiles/cudaRO.dir/build.make CMakeFiles/cudaRO.dir/build
.PHONY : cudaRO/fast

src/genetics/genetics.o: src/genetics/genetics.cpp.o
.PHONY : src/genetics/genetics.o

# target to build an object file
src/genetics/genetics.cpp.o:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/genetics/genetics.cpp.o
.PHONY : src/genetics/genetics.cpp.o

src/genetics/genetics.i: src/genetics/genetics.cpp.i
.PHONY : src/genetics/genetics.i

# target to preprocess a source file
src/genetics/genetics.cpp.i:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/genetics/genetics.cpp.i
.PHONY : src/genetics/genetics.cpp.i

src/genetics/genetics.s: src/genetics/genetics.cpp.s
.PHONY : src/genetics/genetics.s

# target to generate assembly for a file
src/genetics/genetics.cpp.s:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/genetics/genetics.cpp.s
.PHONY : src/genetics/genetics.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ufl/ufl.o: src/ufl/ufl.cpp.o
.PHONY : src/ufl/ufl.o

# target to build an object file
src/ufl/ufl.cpp.o:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/ufl/ufl.cpp.o
.PHONY : src/ufl/ufl.cpp.o

src/ufl/ufl.i: src/ufl/ufl.cpp.i
.PHONY : src/ufl/ufl.i

# target to preprocess a source file
src/ufl/ufl.cpp.i:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/ufl/ufl.cpp.i
.PHONY : src/ufl/ufl.cpp.i

src/ufl/ufl.s: src/ufl/ufl.cpp.s
.PHONY : src/ufl/ufl.s

# target to generate assembly for a file
src/ufl/ufl.cpp.s:
	$(MAKE) -f CMakeFiles/Genny.dir/build.make CMakeFiles/Genny.dir/src/ufl/ufl.cpp.s
.PHONY : src/ufl/ufl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Genny"
	@echo "... cudaRO"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/genetics/genetics.o"
	@echo "... src/genetics/genetics.i"
	@echo "... src/genetics/genetics.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ufl/ufl.o"
	@echo "... src/ufl/ufl.i"
	@echo "... src/ufl/ufl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

